plugin:
    name: 'remideltombe.news::lang.plugin.name'
    description: 'remideltombe.news::lang.plugin.description'
    author: 'Remi Deltombe'
    icon: oc-icon-newspaper-o
    homepage: ''
navigation:
    news:
        label: News
        url: remideltombe/news/items
        icon: icon-newspaper-o
        permissions:
            - remideltombe.news.edit_item
        sideMenu:
            items:
                label: Items
                url: remideltombe/news/items
                icon: icon-newspaper-o
                permissions:
                    - remideltombe.news.edit_item
            categories:
                label: Categories
                url: remideltombe/news/categories
                icon: icon-sort-alpha-asc
                permissions:
                    - remideltombe.news.edit_category
permissions:
    remideltombe.news.edit_item:
        tab: Content
        label: 'Edit news items'
    remideltombe.news.edit_category:
        tab: Content
        label: 'Edit news categories'
