plugin:
    name: 'remideltombe.esport::lang.plugin.name'
    description: 'remideltombe.esport::lang.plugin.description'
    author: 'Remi Deltombe'
    icon: oc-icon-gamepad
    homepage: ''
permissions:
    remideltombe.socialnetworks.manage_game:
        tab: Esport
        label: 'Manage games'
navigation:
    esport:
        label: Esport
        url: remideltombe/esport/results
        icon: icon-gamepad
        permissions:
            - remideltombe.socialnetworks.manage_game
        sideMenu:
            side-menu-item:
                label: Results
                url: remideltombe/esport/results
                icon: icon-sitemap

            side-menu-item2:
                label: Games
                url: remideltombe/esport/games
                icon: icon-gamepad