name: Items
form: $/remideltombe/news/models/item/fields.yaml
modelClass: RemiDeltombe\News\Models\Item
defaultRedirect: remideltombe/news/items
create:
    redirect: 'remideltombe/news/items/update/:id'
    redirectClose: remideltombe/news/items
update:
    redirect: remideltombe/news/items
    redirectClose: remideltombe/news/items
