list: $/remideltombe/news/models/item/columns.yaml
modelClass: RemiDeltombe\News\Models\Item
title: Items
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'remideltombe/news/items/update/:id'
