list: $/remideltombe/esport/models/game/columns.yaml
modelClass: RemiDeltombe\Esport\Models\Game
title: Games
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'remideltombe/esport/games/update/:id'
