plugin:
    name: 'remideltombe.album::lang.plugin.name'
    description: 'remideltombe.album::lang.plugin.description'
    author: 'Remi Deltombe'
    icon: icon-camera-retro
    homepage: ''
permissions:
    remideltombe.album.edit:
        tab: Content
        label: 'Edit albums'
navigation:
    main-menu-item:
        label: Album
        url: remideltombe/album/albums
        icon: icon-camera-retro
