name: Generation
form: $/remideltombe/faker/models/generation/fields.yaml
modelClass: RemiDeltombe\Faker\Models\Generation
defaultRedirect: remideltombe/faker/generation
create:
    redirect: 'remideltombe/faker/generation/update/:id'
    redirectClose: remideltombe/faker/generation
update:
    redirect: remideltombe/faker/generation
    redirectClose: remideltombe/faker/generation
