list: $/remideltombe/faker/models/generation/columns.yaml
modelClass: RemiDeltombe\Faker\Models\Generation
title: Generation
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'remideltombe/faker/generation/update/:id'
