list: $/remideltombe/album/models/album/columns.yaml
modelClass: RemiDeltombe\Album\Models\Album
title: Albums
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'remideltombe/album/albums/update/:id'
