name: PageController
form: $/remideltombe/page/models/page/fields.yaml
modelClass: RemiDeltombe\Page\Models\Page
defaultRedirect: remideltombe/page/pagecontroller
create:
    redirect: 'remideltombe/page/pagecontroller/update/:id'
    redirectClose: remideltombe/page/pagecontroller
update:
    redirect: remideltombe/page/pagecontroller
    redirectClose: remideltombe/page/pagecontroller
